### ISSUE TITLE
Python guide dead ends

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/docs.snapcraft.io#106]
[The Python docs](https://docs.snapcraft.io/python-apps/6741) close with the following paragraph:
```
Next steps

That’s it. You now have a snapcraft.yaml file which describes how the core of your app is assembled, presented, and run.

Continue on to learn how you can bundle your app’s dependencies, such as system libraries, into this snap so your app is portable across Linux distributions.
```

This dead ends. There are no links to continue and, I believe, no docs to cover adding additional dependencies to a snap.

Should we remove this paragraph for now, or leave this bug open as a reminder to link "next steps" off to something?

**Comment by nottrobin** [comment]
Please discuss this in [the forum post](https://forum.snapcraft.io/t/python-apps/6741). This repository is only for issues with the codebase.
