### ISSUE TITLE
Consistent examples in reference documentation

### ISSUE THREAD

**Issue by igorljubuncic** [canonical-websites/docs.snapcraft.io#107]
Some of the snapcraft reference pages have detailed examples whereas some do not.

All reference pages should have meaningful, non-trivial examples that showcase the usage, including:

- Development implementation (snapcraft.yaml)
- User-side implementation (snap commands)
- Troubleshooting (snappy debug)

- There should be additional examples for language-specific declarations, e,g, rust, go, python.
- Links to language guides

**Example**

Good documentation:
https://docs.snapcraft.io/interface-management/6154

Insufficient documentation:
https://docs.snapcraft.io/interface-hooks/8214

**Comment by nottrobin** [comment]
The content of documentation is entirely managed in the forum. To contribute to this content please discuss it in https://forum.snapcraft.io/t/interface-management/6154 and https://forum.snapcraft.io/t/how-to-fetch-a-snap-source-snapcraft-yaml/9799.

This repository is only for managing the codebase for docs.snapcraft.io.
