### ISSUE TITLE
Publishing missing from "Snap Documentation" index page

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/docs.snapcraft.io#116]
The index page covers "discovering snaps", "building snaps", but not "publishing snaps". We could in this place talk about the Snap Store. There is much to say about uploading new releases; setting a logo, category, screenshots, videos, and markdown so that snapcraft.io/app is your best marketing; and measuring uptake of your application through metrics.

**Comment by nottrobin** [comment]
The index content is kept in the forum here:

https://forum.snapcraft.io/t/snap-documentation/3781

Please discuss or suggest any changes to the index page in the forum.

**Comment by evandandrea** [comment]
@nottrobin the forum is not a bug tracker. Once we had more than a few notes of documentation gaps it would become very difficult to track in the forum.

**Comment by nottrobin** [comment]
@evandandrea yes I can appreciate you might want to track some issues with the content outside the forum, even though I'd think you'd want to make sure forum users had visibility over your proposed changes (that's sort of the point of Discourse)

But I don't think this repository is the place. With the new Discourse model, this repository, owned by our team, is literally just the application that presents the Discourse content as a website. our team now has no ownership over the content. We no longer have any documentation people working in our team. The snap squad who will see these issues appear on their stand-up board are only web developers and designers, for whom content issues mean very little.

I'd suggest you set up somewhere else to track issues with the documentation content.
