### ISSUE TITLE
Missing xubuntu instructions

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/docs.snapcraft.io#122]
A visitor to snapcraft.io used Intercom to ask how they install Spotify on Xubuntu. While we have Ubuntu install instructions, we don't have Xubuntu ones. I realise the steps are the same, but it would be helpful (and good SEO) to mention Xubuntu on https://docs.snapcraft.io/installing-snapd/6735.

**Comment by nottrobin** [comment]
Could you please find somewhere else to track issues with the forum content, if the forum itself isn't appropriate? (See https://github.com/canonical-websites/docs.snapcraft.io/issues/116#issuecomment-463526387)
