### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by jamesbeedy** [canonical-websites/docs.snapcraft.io#59]
"snapcraft lifecycle" link doesn't seem to work on this page https://docs.snapcraft.io/snapcraft-yaml-reference/4276

<img width="859" alt="screen shot 2018-11-01 at 3 00 38 am" src="https://user-images.githubusercontent.com/5590546/47845555-97f98800-dd82-11e8-8027-267318fcdcf2.png">

**Comment by nottrobin** [comment]
Thanks @jamesbeedy 

This page can be discussed or edited directly [in the forum](https://forum.snapcraft.io/t/snapcraft-yaml-reference/4276). Please make the change there.

This repository is only for managing the application code for docs.snapcraft.io.
