### ISSUE TITLE
Wrapping command examples

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/docs.snapcraft.io#62]
Hi,

Consider https://docs.snapcraft.io/build-on-docker/4158

It renders as:
```
sudo docker pull snapcore/snapcraft
sudo docker run -v "$PWD":/snapcraft_build -w /snapcraft_build snapcore/snapcraft 
snapcraft
```

This looks like three commands, but it's actually two. The latter command is:
```
sudo docker run -v "$PWD":/snapcraft_build -w /snapcraft_build snapcore/snapcraft snapcraft
```

Do we have a solution for avoiding such ambiguity with commands that would force a line wrap?

**Comment by degville** [comment]
The Docker page has now been updated, fixing this issue.

**Comment by joaomoreno** [comment]
:clap:
