### ISSUE TITLE
confinement docs missing

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/docs.snapcraft.io#64]
https://docs.snapcraft.io/reference/confinement used to point at a page on confinement, and as such is linked to in our automated emails on "getting a snap ready for a stable release." This now 410s.

I'd welcome suggestions on how we can change the copy of this email to reflect the current documentation:

>### Ready to reach a wider audience for `$SNAP`?
>Let users discover your snap from the command line or any graphical storefront. Here’s how:
>* [Choose](https://docs.snapcraft.io/reference/confinement) a security policy.
>* [Provide](https://docs.snapcraft.io/build-snaps/syntax) a title, description, screenshot(s) and icon so your app features well in listings.
>* [Release](
https://docs.snapcraft.io/reference/channels#releasing-a-snap) to the stable channel.

/cc @degville

**Comment by popey** [comment]
Looks like this is the page it should redirect to. https://docs.snapcraft.io/snap-confinement/6233
