### ISSUE TITLE
Classic request documentation missing

### ISSUE THREAD

**Issue by popey** [canonical-websites/docs.snapcraft.io#66]
Related to #64 I can't find any doc at docs.snapcraft.io which outlines the process for requesting classic confinement. I'm looking for somewhere to link new developers to, who will be making a classic snap, but need to understand the implications, and more importantly the process for how to request classic snaps.

As an insider, I happen to know (but had to search pretty hard for) [this page](https://forum.snapcraft.io/t/process-for-reviewing-classic-confinement-snaps/1460) on the forum. Also, as an insider, I knew I can monkey that url to become [this url](https://docs.snapcraft.io/process-for-reviewing-classic-confinement-snaps/1460) in the docs, but that's not acceptable for external developers.

Please can we expose the publishing docs prominently on the docs site. Thanks.

**Comment by nottrobin** [comment]
Content is managed in [the forum](https://forum.snapcraft.io).

New page can be added as topics in the forum "docs" category and then you can ask for them to be included in [the navigation topic](https://forum.snapcraft.io/t/snap-documentation/3781), if relevant. Or you can discuss which pages should be created in the forum.

This repository is only for managing the application code.
