### ISSUE TITLE
Broken links on yaml reference page

### ISSUE THREAD

**Issue by popey** [canonical-websites/docs.snapcraft.io#69]
https://docs.snapcraft.io/snapcraft-yaml-reference/4276#build-attributes

Some links on the page are broken. Noted these at the bottom:-

![image](https://user-images.githubusercontent.com/1841272/48635341-c8b30180-e9bf-11e8-9fbc-d309130c0a93.png)

The source has `<a>snapcraft plugins</a>` with no links.

**Comment by nottrobin** [comment]
This content can be edited directly, or discussed, [in the forum](https://forum.snapcraft.io/t/snapcraft-yaml-reference/4276). Please continue discussion there.

This repository is just for managing the application code.
