### ISSUE TITLE
what is a base?

### ISSUE THREAD

**Issue by sergiusens** [canonical-websites/docs.snapcraft.io#70]
There is no documentation explaining what a base is.

**Comment by evandandrea** [comment]
This was tackled in the first snap flow here: https://github.com/canonical-websites/snapcraft.io/commit/a7bb9b3b4dbb493e6ff4413c5b968098b7032216#diff-8c98e32d4273f570ec093f6d34c1070c

We should make these consistent/rewrite with the addition to docs.snapcraft.io.

**Comment by nottrobin** [comment]
I'm closing this for now. Please continue discussion of terms in the [forum](https://forum.snapcraft.io).
