### ISSUE TITLE
Docs search is Ubuntu-branded

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/docs.snapcraft.io#78]
Snapcraft and the Snap Store are distribution-neutral. However, the just-landed docs.snapcraft.io search (#75) takes you to ubuntu.com.

Can we fix this to be snapcraft.io hosted?

**Comment by matthewpaulthomas** [comment]
Ideally, the fix for this should simultaneously remove the external-link icon from the “Search” button.

**Comment by jpmartinspt** [comment]
Will be fixed by https://github.com/canonical-websites/docs.snapcraft.io/issues/129
