### ISSUE TITLE
Spurious search result for “gitlab”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/docs.snapcraft.io#80]
1\. [Search the docs for “gitlab”](https://www.ubuntu.com/search?siteSearch=docs.snapcraft.io&q=gitlab).

What happens: One search result, [“Releasing to the Snap Store - Documentation for snaps: Universal ...”](https://docs.snapcraft.io/releasing-to-the-snap-store/6848), which does not mention “gitlab” or anything like it.

What should happen: The search does not return pages unless they contain the search term (or spelling or grammar variation).

**Comment by nottrobin** [comment]
Unfortunately we can't have much control over this. Search uses the Google Custom Search service, and will continue to use that service even when we better integrate it with https://snapcraft.io.

The only way I'm aware of to fix this would be to lobby Google to change their algorithm. Or switch away from Google Custom Search, but I think we'd need far more examples of undesirable results than this to justify the latter.
