### ISSUE TITLE
Missing links to continue learning pages

### ISSUE THREAD

**Issue by afterconnery** [canonical-websites/docs.snapcraft.io#82]
The bottom paragraph, under the "Next Steps" heading, on creating a Electron snap is missing links to other pages for continued learning. 

https://docs.snapcraft.io/electron-apps/6748

Actually on all the specific common languages pages for creating a snap the hyperlinks are missing.

**Comment by nottrobin** [comment]
Hi @afterconnery 

You should be able to contribute to this document directly by editing the forum post linked from the bottom of that page:

https://forum.snapcraft.io/t/electron-apps/6748

Or you can simply add a comment to the post if you want feedback on the suggestion.

This repository is only for managing the docs.snapcraft.io application code.
