### ISSUE TITLE
Ruby documentation does not work with bases

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/docs.snapcraft.io#94]
The ruby documentation suggests using `build` and `install`, but these have been replaced with `override-build` when using bases.

https://docs.snapcraft.io/ruby-applications/7824

/cc @sergiusens

**Comment by evandandrea** [comment]
As well, it refers to an old version of ruby in stage-packages.

**Comment by nottrobin** [comment]
Please discuss or directly edit this content [in the forum post](https://forum.snapcraft.io/t/ruby-applications/7824). This repository is for the docs.snapcraft.io codebase only.
